export const designations = [
  { value: "PRINCIPAL", label: "Principal" },
  { value: "ESTATE_OFFICER", label: "Estate Officer" },
  {
    value: "ASSISTANT_TO_ESTATE_OFFICER",
    label: "Assistant to Estate Officer",
  },
  { value: "COMPLAINANT", label: "Complainant" },
  { value: "EXECUTIVE_ENGINEER_CIVIL", label: "Executive Engineer (Civil)" },
  {
    value: "EXECUTIVE_ENGINEER_ELECTRICAL",
    label: "Executive Engineer (Electrical)",
  },
  { value: "ASSISTANT_ENGINEER_CIVIL", label: "Assistant Engineer (Civil)" },
  {
    value: "ASSISTANT_ENGINEER_ELECTRICAL",
    label: "Assistant Engineer (Electrical)",
  },
  { value: "JUNIOR_ENGINEER_CIVIL", label: "Junior Engineer (Civil)" },
  {
    value: "JUNIOR_ENGINEER_ELECTRICAL",
    label: "Junior Engineer (Electrical)",
  },
];

export const statusOptions = {
  RAISED: [
    { value: "JE_ACKNOWLEDGED", label: "JE Acknowledged" },
    { value: "RESOURCE_REQUIRED", label: "Resource Required" },
  ],
  JE_WORKDONE: [
    { value: "AE_ACKNOWLEDGED", label: "AE Approved" },
    { value: "AE_NOT_SATISFIED", label: "AE Not Satisfied" },
  ],
  AE_ACKNOWLEDGED: [
    { value: "EE_ACKNOWLEDGED", label: "EE Approved" },
    { value: "EE_NOT_SATISFIED", label: "EE Not Satisfied" },
  ],
  EE_ACKNOWLEDGED: [{ value: "RESOLVED", label: "Resolved" }],
  RESOURCE_REQUIRED: [
    { value: "CLOSED", label: "Closed" },
    { value: "RAISED", label: "Raised" },
  ],
  EE_NOT_SATISFIED: [
    { value: "AE_NOT_SATISFIED", label: "AE Not Satisfied" },
    { value: "AE_ACKNOWLEDGED", label: "AE Approved" },
  ],
  JE_ACKNOWLEDGED: [{ value: "JE_WORKDONE", label: "JE Work Done" }],
  AE_NOT_SATISFIED: [{ value: "JE_WORKDONE", label: "JE Work Done" }],
};

export const locationOptions = {
  "Vana Vigyan Building - Ground Floor": [
    "Admin Section",
    "Training Section",
    "Principal Sir's Room",
    "Staff Toilet",
    "Officer - Gents Toilet",
    "Corbett Hall",
    "Library ",
    "V C Room",
    "GIS Lab",
    "Officier Trainee - Gents Toilets",
    "Officier Trainee - LadiesToilets",
    "Lady officier's Toilet",
    "Corridor",
    "Godown",
    "Store",
    "Parking Shed",
    "Main Gate",
  ],
  "Vana Vigyan Building - First Floor": [
    "Faculty Chamber ",
    "GD rooms",
    "IT Room",
    "PT and GI room",
    "UPS room",
    "Officer - Gents Toilet",
    "Classroom - 1",
    "Classroom - 2",
    "Champion Hall",
    "Lab",
    "Officer Traineer - Gents Toilet",
    "Officer Traineer - Ladies Toilet",
    "Corridor",
  ],
  "Vana Vatika": ["Common Area", "VIP Room", "Toilet", "Green Room"],
  "Chandan Hostel": [
    "Reception",
    "Mess",
    "A-Block",
    "B-Block",
    "Common Toilets",
    "Corridor",
    "Terrace",
  ],
  "Executive Hostel": [
    "Reception Area",
    "Suit Rooms",
    "Rooms",
    "Common Toilet",
    "Corridor",
    "Outer Area",
  ],
  "Sports Ground": [
    "GYM",
    "Pavilion Building",
    "Store room",
    "PT and GI room",
    "Snooker Hall",
    "Tennis Court",
    "Volley Ball Court",
    "Rest room - Gents",
    "Rest room - Ladies",
    "Basket Ball Court",
    "Badminton Court",
  ],
  Quarters: [
    "A-5 Quarters",
    "A-2 Quarters",
    "Type-5 ",
    "Type-4",
    "Type-3",
    "Type-2",
    "Type-1",
    "Servent Quarters",
  ],
  "Mess Building": [
    "Dining Room",
    "Kitchen",
    "Rest room - Gents",
    "Rest room - Ladies",
    "Corridor",
    "Parking Area",
  ],
  "Ladies Hostel": [
    "Rooms",
    "Washing area",
    "Corridor",
    "Reception",
    "Parking Area",
  ],
};

export const subjectOptions = [
  "Water Leaking",
  "Light Not Working",
  "Fan Not Working",
  "AC Not Working",
  "Internet Not Working",
  "Drainage Block",
  "Water Sewage",
  "Motor Not Working",
  "Toilet Flush/HandWash set Not Working",
  "No Power Supply",
];
